name: build-cli

on:
  workflow_dispatch:

jobs:
  build-cli:
    name: ${{ matrix.os }} - ${{ matrix.backend }}
    runs-on: sdk-windows-8-core-2
    strategy:
      fail-fast: false
      matrix:
        os: [windows]
        backend: [llama-cpp-cpu, llama-cpp-vulkan, llama-cpp-cuda]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
          cache-dependency-path: runner/go.sum

      - name: Build Nexa Cli
        run: make build

      - name: Download runtime
        run: |
          make download BRIDGE_BACKEND=${{ matrix.backend }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nexasdk-cli_${{ matrix.os }}_${{ matrix.backend }}
          path: ./build
