name: NexaCLI on Windows

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-cli:
    name: ${{ matrix.os }} - ${{ matrix.backend }}
    runs-on: sdk-windows-8-core-2
    strategy:
      fail-fast: false
      matrix:
        os: [windows]
        backend: [llama-cpp-cpu, llama-cpp-vulkan, llama-cpp-cuda]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect Tag Version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=${{ github.ref_name }}" >> $env:GITHUB_ENV

      - name: Detect Commit Hash
        if: github.event_name == 'workflow_dispatch'
        run: |
          $shortHash = "${{ github.sha }}".Substring(0, 7)
          echo "VERSION=$shortHash" >> $env:GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
          cache-dependency-path: runner/go.sum

      - name: Setup MinGW
        run: choco install mingw -y

      - name: Build Nexa Cli
        run: make build

      - name: Download runtime
        run: |
          make download BRIDGE_BACKEND=${{ matrix.backend }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nexa-cli_${{ matrix.os }}_${{ matrix.backend }}
          path: build
          include-hidden-files: true

  build-installer:
    name: Build Windows Installer & Release
    runs-on: sdk-windows-8-core-2
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: build-cli
    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install pyinstaller

      - name: Build launcher with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --distpath artifacts --name "nexa-cli-launcher" --icon="release/nexa_logo.ico" release/nexa_windows_launcher.py

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 8.0.403

      - name: Sign executables with AzureSignTool
        shell: pwsh
        run: |
          dotnet tool install --global AzureSignTool

          Get-ChildItem -Path "artifacts" -Recurse -Include *.exe, *.dll | ForEach-Object {
            azuresigntool sign `
              -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" `
              -kvc "${{ secrets.AZURE_CERT_NAME }}" `
              -kvi "${{ secrets.AZURE_CLIENT_ID }}" `
              -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" `
              --azure-key-vault-tenant-id "${{ secrets.AZURE_TENANT_ID }}" `
              -tr http://timestamp.globalsign.com/tsa/advanced `
              -td sha256 `
              $_.FullName
          }

          azuresigntool sign `
            -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" `
            -kvc "${{ secrets.AZURE_CERT_NAME }}" `
            -kvi "${{ secrets.AZURE_CLIENT_ID }}" `
            -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" `
            --azure-key-vault-tenant-id "${{ secrets.AZURE_TENANT_ID }}" `
            -tr http://timestamp.globalsign.com/tsa/advanced `
            -td sha256 `
            "artifacts\nexa-cli-launcher.exe"

      - name: Compile Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.6
        with:
          path: release/nexa_installer.iss
          options: /O+

      - name: Sign Installer
        shell: pwsh
        run: |
          azuresigntool sign `
            -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" `
            -kvc "${{ secrets.AZURE_CERT_NAME }}" `
            -kvi "${{ secrets.AZURE_CLIENT_ID }}" `
            -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" `
            --azure-key-vault-tenant-id "${{ secrets.AZURE_TENANT_ID }}" `
            -tr http://timestamp.globalsign.com/tsa/advanced `
            -td sha256 `
            "artifacts/nexa-cli_windows-setup.exe"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          repository: zhiyuan8/homebrew-go-release
          tag_name: ${{ env.VERSION }}
          files: artifacts/nexa-cli_windows-setup.exe
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.NEXASDK_RELEASE_TOKEN }}
