name: build-cli

on:
  workflow_dispatch:

jobs:
  build-cli:
    name: Build cli on ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: ubuntu_22.04
            runner: sdk-linux-16-core
          - name: macos_13
            runner: macos-13
          - name: macos_14
            runner: macos-14
          - name: macos_15
            runner: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: remilia/dev

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
          cache-dependency-path: runner/go.sum

      - name: Build Nexa Cli
        run: make build

      - name: Download runtime
        run: |
          make download
          mv build nexasdk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nexasdk_${{ matrix.name }}
          path: ./nexasdk
