name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false  # This allows all matrix jobs to complete even if one fails
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive  # This will clone the repository with all its submodules
        fetch-depth: 0  # This fetches all history so you can access any version of the submodules

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build pytest
      shell: bash

    - name: Install CMake (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install cmake
      shell: bash

    - name: Install CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      shell: bash

    - name: Setup MinGW (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make

    - name: Build DLL (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        export PATH="/c/hostedtoolcache/windows/Python/${{ matrix.python-version }}.11/x64:/c/hostedtoolcache/windows/Python/${{ matrix.python-version }}.11/x64/Scripts:$PATH"
        CMAKE_ARGS="-DCMAKE_CXX_FLAGS=-fopenmp"
        /c/hostedtoolcache/windows/Python/${{ matrix.python-version }}.11/x64/python.exe -m pip install -e .

    - name: Build (macOS)
      if: runner.os == 'macOS'
      run: |
        CMAKE_ARGS="-DCMAKE_CXX_FLAGS=-fopenmp"
        python -m pip install -e .
      shell: bash

    - name: Run tests
      run: |
        python -m pytest tests
      shell: bash